### We are going to work with a Linear Regression Model to learn the relationship between the columns in our data and then Predict the Gross National Income of the Gambia in the coming Years.

In [15]:
# Importing the neccesary libraries that we will be working with
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline
from sklearn.linear_model import LinearRegression

In [4]:
# Using pandas to read in out dataset and only use our specified colums
data = pd.read_csv('Gambia_Gross National Income.csv',usecols=('Year','GNI'))

In [5]:
# Taking a look at the top hows in our dataset
data.head()

Year   GNI
0  1990  1329
1  1991  1393
2  1992  1395
3  1993  1394
4  1994  1354

In [7]:
'''Getting summary of the data, including the number of rows and columns, the 
data types of each column, and the number of non-null values in each column'''
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    29 non-null     int64
 1   GNI     29 non-null     int64
dtypes: int64(2)
memory usage: 596.0 bytes


In [18]:
# Using the searborn regplot method to visualize the relations between our data
plt.style.use('bmh')
plt.figure(figsize=(15,8))
sns.pointplot(x='Year' ,y = 'GNI', data=data,color='green')

<Axes: xlabel='Year', ylabel='GNI'>

In [6]:
'''Creating  a linear regression model using the LinearRegression class from scikit-learn to train our model. 
It fits the model to the data, using the Year column as the 
independent variable and the GNI column as the dependent variable.'''
model = LinearRegression()
model.fit(data[['Year']].values, data.GNI)

LinearRegression()

In [7]:
# Predict the GNI for the year 2019 using the trained linear regression model
prediction = model.predict([[2019]])
prediction

array([1455.27832512])

In [8]:
# Predict the GNI for the year 2020 using the trained linear regression model
prediction = model.predict([[2020]])
prediction

array([1459.33596059])

In [9]:
# Predict the GNI for the year 2021 using the trained linear regression model
prediction = model.predict([[2021]])
prediction

array([1463.39359606])

In [10]:
# Predict the GNI for the year 2022 using the trained linear regression model
prediction = model.predict([[2022]])
prediction

array([1467.45123153])

In [11]:
# Predict the GNI for the year 2023 using the trained linear regression model
prediction = model.predict([[2023]])
prediction

array([1471.508867])